### ISSUE TITLE
Support for Sveltekit 2

### ISSUE THREAD

**Issue by tomjnsn** [wackfx/adapter-cloudflare-node#1]
Thanks for taking the time to provide the adapter-cloudflare-node fork that allows usage of nodejs_compat in cloudflare pages for sveltekit. With the new version 2 of sveltekit out it isn't possible to use because of the `peerDependency` of `@sveltejs/kit: ^1.x.x`. I have forked it and tried it on a sveltekit 2 app and it appears to be working fine. Is that something you'd consider updating? I'm not sure how long it will be until `adapter-cloudflare` will support `nodejs_compat`.

**Comment by wackfx** [comment]
Hey, sure I will take a look into it tonight, thanks for the heads up

**Comment by wackfx** [comment]
This should be OK :)
